#!/usr/bin/env python3

# ========== INCIDENT REPORT GENERATOR ==========
import os
from datetime import datetime

LOG_FILE = "/home/ubuntu/skinfo24/logs/monitor.log"
REPORT_DIR = "/home/ubuntu/skinfo24/reports"
DATE = datetime.now().strftime("%Y-%m-%d")
TIME = datetime.now().strftime("%H:%M:%S")

os.makedirs(REPORT_DIR, exist_ok=True)

total = 0
up = 0
down = 0
incidents = []

with open(LOG_FILE, "r") as f:
    for line in f:
        total += 1
        if "✅" in line:
            up += 1
        elif "❌" in line:
            down += 1
            incidents.append(line.strip())

uptime = round((up / total) * 100, 2) if total > 0 else 0

report = f"""
========================================
   INCIDENT REPORT — {DATE}
   Generated at: {TIME}
========================================

SUMMARY:
  Total Checks    : {total}
  Website UP      : {up}
  Website DOWN    : {down}
  Uptime          : {uptime}%

INCIDENTS:
"""

if incidents:
    for i in incidents:
        report += f"  {i}\n"
else:
    report += "  No incidents recorded. Website was UP all time!\n"

report += """
========================================
   Report generated by skinfo24 monitor
========================================
"""

report_file = f"{REPORT_DIR}/incident_report_{DATE}.txt"
with open(report_file, "w") as f:
    f.write(report)

print(report)
print(f"Report saved to: {report_file}")